import './globals.css'
import 'react-toastify/dist/ReactToastify.css'
import 'react-loading-skeleton/dist/skeleton.css'
import 'swiper/css'
import type { Metadata } from 'next'
import React from 'react'
import { ToastContainer } from 'react-toastify'
import { getLocale, getMessages } from 'next-intl/server'
import { NextIntlClientProvider } from 'next-intl'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
	const locale = await getLocale()
	const messages = await getMessages()
	return (
		<html lang={locale}>
			<body>
				<div id='__next'>
					<ToastContainer className='w-auto' />
					<NextIntlClientProvider messages={messages}>{children}</NextIntlClientProvider>
				</div>
			</body>
		</html>
	)
}
